# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('_rg', models.PositiveSmallIntegerField(unique=True, verbose_name='RG')),
                ('_especie', models.CharField(max_length=50, verbose_name='Esp\xe9cie')),
                ('_raca', models.CharField(max_length=50, verbose_name='Ra\xe7a')),
                ('sexo', models.CharField(choices=[('FE', 'Feminino'), ('MA', 'Masculino')], max_length=15, verbose_name='Sexo')),
                ('_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('_idade', models.PositiveSmallIntegerField(verbose_name='Idade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data de Realiza\xe7\xe3o')),
                ('diagnostico', models.TextField(max_length=200, verbose_name='Diagn\xf3stico')),
                ('retorno', models.BooleanField(default='False')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='a_ser_consultado', to='cadastro.Animal')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data de Realiza\xe7\xe3o')),
                ('diagnostico', models.TextField(max_length=200, verbose_name='Diagn\xf3stico')),
                ('resultado', models.TextField(max_length=200, verbose_name='Diagn\xf3stico')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amostrado_para_exame', to='cadastro.Animal')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Exames',
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TutorEndTel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('_numero', models.PositiveSmallIntegerField(verbose_name='N\xfamero')),
                ('_bairro', models.CharField(max_length=20, verbose_name='Bairro')),
                ('_cidade', models.CharField(max_length=200, verbose_name='Cidade')),
                ('_cep', models.CharField(max_length=15, verbose_name='CEP')),
                ('_uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amap\xe1'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Cear\xe1'), ('DF', 'Distrito Federal'), ('ES', 'Esp\xedrito Santo'), ('GO', 'Goi\xe1s'), ('MA', 'Maranh\xe3o'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Par\xe1'), ('PB', 'Para\xedba'), ('PR', 'Paran\xe1'), ('PE', 'Pernambuco'), ('PI', 'Piau\xed'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rond\xf4nia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'S\xe3o Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=10, verbose_name='UF')),
                ('_telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('tipo', models.CharField(choices=[('Fixo', 'Fixo'), ('Celular', 'Celular')], max_length=15)),
                ('_nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('_email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('_cpf', models.CharField(max_length=11, verbose_name='CPF')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='exame',
            name='tecnico',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realiza_exame', to='cadastro.Tecnico'),
        ),
        migrations.AddField(
            model_name='exame',
            name='veterinario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realiza_diagnostico', to='cadastro.Veterinario'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='veterinario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realiza_consulta', to='cadastro.Veterinario'),
        ),
        migrations.AddField(
            model_name='animal',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.TutorEndTel'),
        ),
    ]
