# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-07 22:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('_rg', models.PositiveSmallIntegerField(blank=True, unique=True, verbose_name='RG')),
                ('_especie', models.CharField(max_length=50, verbose_name='Esp\xe9cie')),
                ('_raca', models.CharField(max_length=50, verbose_name='Ra\xe7a')),
                ('sexo', models.CharField(choices=[('FE', 'Feminino'), ('MA', 'Masculino')], max_length=15, verbose_name='Sexo')),
                ('_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('_obito', models.DateField(blank=True, null=True, verbose_name='Data de \xd3bito')),
                ('_idade', models.PositiveSmallIntegerField(verbose_name='Idade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AtendimentoAbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_data', models.DateField(auto_now_add=True)),
                ('_diagnostico', models.TextField(blank=True, default='Pendente', max_length=200, verbose_name='Diagn\xf3stico')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('_local', models.CharField(max_length=50, verbose_name='local')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('_email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('_cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('_crf', models.CharField(max_length=10, verbose_name='CRF')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Tecnicos',
            },
        ),
        migrations.CreateModel(
            name='TutorEndTel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('_numero', models.PositiveSmallIntegerField(verbose_name='N\xfamero')),
                ('_bairro', models.CharField(max_length=20, verbose_name='Bairro')),
                ('_cidade', models.CharField(max_length=200, verbose_name='Cidade')),
                ('_cep', models.CharField(max_length=15, verbose_name='CEP')),
                ('_uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amap\xe1'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Cear\xe1'), ('DF', 'Distrito Federal'), ('ES', 'Esp\xedrito Santo'), ('GO', 'Goi\xe1s'), ('MA', 'Maranh\xe3o'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Par\xe1'), ('PB', 'Para\xedba'), ('PR', 'Paran\xe1'), ('PE', 'Pernambuco'), ('PI', 'Piau\xed'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rond\xf4nia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'S\xe3o Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=10, verbose_name='UF')),
                ('_telefone1', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="O formato do n\xfamero de telefone deve ser: '+999999999'. S\xe3o Permitidos at\xe9 15 d\xedgitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone de Contato 1')),
                ('_telefone2', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="O formato do n\xfamero de telefone deve ser: '+999999999'. S\xe3o Permitidos at\xe9 15 d\xedgitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone de Contato 2')),
                ('_nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('_email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('_cpf', models.CharField(max_length=11, verbose_name='CPF')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('_email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('_cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('_crmv', models.CharField(max_length=10, verbose_name='CRMV')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Veterinarios',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('atendimentoabs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cadastro.AtendimentoAbs')),
                ('_retorno', models.BooleanField()),
                ('_data_realizacao', models.DateField(verbose_name='Data Agendada')),
            ],
            options={
                'abstract': False,
            },
            bases=('cadastro.atendimentoabs',),
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('atendimentoabs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cadastro.AtendimentoAbs')),
                ('_resultado', models.TextField(blank=True, default='Pendente', max_length=200, verbose_name='Resultado')),
                ('observacoes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observa\xe7\xf5es')),
                ('numero_amostra', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='N\xfamero de amostra')),
                ('estadoexame', models.NullBooleanField(verbose_name='Estado do Exame')),
            ],
            options={
                'abstract': False,
            },
            bases=('cadastro.atendimentoabs',),
        ),
        migrations.AddField(
            model_name='atendimentoabs',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_a_ser_atendido', to='cadastro.TutorEndTel'),
        ),
        migrations.AddField(
            model_name='animal',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='cadastro.TutorEndTel'),
        ),
        migrations.AddField(
            model_name='exame',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mostrado_para_exame', to='cadastro.Animal'),
        ),
        migrations.AddField(
            model_name='exame',
            name='laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='cadastro.Laboratorio'),
        ),
        migrations.AddField(
            model_name='exame',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realiza_exame', to='cadastro.Tecnico'),
        ),
        migrations.AddField(
            model_name='exame',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realiza_diagnostico', to='cadastro.Veterinario'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_ser_consultado', to='cadastro.Animal'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realiza_consulta', to='cadastro.Veterinario'),
        ),
    ]
